CREATE DATABASE MB_DATABASE;
CREATE USER 'MB_USER'@'%' IDENTIFIED BY 'MB_PASSWORD';
GRANT ALL PRIVILEGES ON MB_DATABASE.* TO 'MB_USER'@'%' IDENTIFIED BY 'MB_PASSWORD';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'MB_ROOT_PASSWORD';